//home
export const LOAD_LIST_FILM_REQUEST = 'LOAD_LIST_FILM_REQUEST';
export const LOAD_LIST_FILM_SUCCESS = 'LOAD_LIST_FILM_SUCCESS';

export const LOAD_LIST_USER_REQUEST = 'LOAD_LIST_USER_REQUEST';
export const LOAD_LIST_USER_SUCCESS = 'LOAD_LIST_USER_SUCCESS';








export const DESTROY_SESSION = 'DESTROY_SESSION';